### PR TITLE
Merge ign-rendering2 to ign-rendering3 

### PR DESCRIPTION
**Pull request by iche033**
Merging forward 2 to 3 so we can run ogre2 tests with the latest depth camera noise changes on jenkins

### CODE REVIEW

**Comment by iche033** [comment]
depth and render pass test also failed here. Marking this PR as draft for debugging

**Comment by iche033** [comment]
@osrf-jenkins run tests please

**Comment by iche033** [comment]
@osrf-jenkins run tests please

**Comment by iche033** [comment]
Ready for review. Ubuntu tests are passing now and I disabled the render_pass integration test in homebrew like we did for the depth camera integration test.

**Review by chapulina — APPROVED** [review]
Changes LGTM. I'm just concerned about the Windows build. " Build finished. No test results found. " usually means the compilation failed, but at the moment build.osrf isn't reachable.

**Comment by iche033** [comment]
the windows machine could be in a bad state. I had to go in from time to time and remove the `build` directory for the next build to pass. I'll give that a try

**Comment by iche033** [comment]
@osrf-jenkins run tests please

**Comment by chapulina** [comment]
The Windows build is indeed broken and I'm not sure exactly why. I triggered a Windows build of `ign-rendering3` just to have a baseline:

[Build Status](https://build.osrfoundation.org/job/ign_rendering-ign-3-win/25/)

**Comment by iche033** [comment]
@osrf-jenkins run tests please

**Comment by iche033** [comment]
> The Windows build is indeed broken and I'm not sure exactly why

I logged into the machine and found that one of the installed ign-common header files is corrupt and had weird characters in it. I deleted the install dir and started another round of builds

**Comment by iche033** [comment]
ok deleting the cached files on the windows CI machine worked. Latest ign-rendering build finished with 2 unrelated test failures

**Comment by chapulina** [comment]
I squashed all the commits that were made on top of the merge, ending at 963e5837d5def175ef25870ad76b13c315dc36c4. For some reason git didn't keep the original author, sorry @iche033 :confused: I'm still figuring out the best way of handling this. And also it looks like I caused some regression on the CI tests, so ultimate #fail :cry:

**Comment by chapulina** [comment]
Reverted the PR back to its original state. I think we can merge it like this unless someone is inclined to try squashing all those commits again.

**Comment by iche033** [comment]
I'm good as is. Let's merge it!

**Comment by chapulina** [comment]
humm so, now the Ubuntu CI has 14 test failures again. I thought I had introduced those with my git gymnastics. Are they expected?

**Comment by iche033** [comment]
No the test failures are not expected. Not sure what happened as the ubuntu builds have been green when I was fixing the window builds. I'll need to take a closer look.

**Comment by iche033** [comment]
@osrf-jenkins run tests please

**Comment by iche033** [comment]
@osrf-jenkins

**Comment by iche033** [comment]
@osrf-jenkins

**Comment by iche033** [comment]
@osrf-jenkins run tests please

**Comment by iche033** [comment]
the latest ubuntu build passed. I think tests started failing on r2d2.nv.xenial recently. I see that the rendering tests are also failing in ign-gazebo with the same unsupported framebuffer format ogre error when run on r2d2, e.g. [this one](https://build.osrfoundation.org/job/ignition_gazebo-ci-pr_any-ubuntu_auto-amd64/4113/#showFailuresLink). I've seen [those errors before](https://answers.gazebosim.org//question/29/gzclient-throwing-ogreinvalidparametersexception/) and usually it's an issue with the graphics driver. I logged onto r2d2 and but couldn't tell if there were any changes in configuration recently. We can try updating the nvidia driver on r2d2 and see if it helps

**Pull request merged**
