### PR TITLE
Visualize wireframes

### PR DESCRIPTION
**Pull request by atharva-18**
# 🎉 New feature

## Summary
Adds wireframe mode to visuals in OGRE 1 and 2.

OGRE 2
wireframe
OGRE 1
wireframe_ogre

## Test it
Test it with [visualize_wireframes](https://github.com/atharva-18/ign-gazebo/tree/visualize_wireframes).

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by atharva-18** [comment]
ogre2_shadow
Wireframe mode in OGRE 2 is creating shadows that don't seem to be correct. Is this the desired behavior?

**Comment by iche033** [comment]
nice, thanks for the contribution! There is a difference between how ogre and ogre2 handles shadows, e.g. semi-transparent objects also cast shadows in ogre2. We'll probably need to explicitly set cast shadows to be off in ogre2.

We promise ABI compatibility for released versions. Adding new virtual functions breaks ABI so these changes will need to go into the `main` branch and to be released in Ignition Fortress. Do you need this functionality in Dome? If so, we can try get these changes into `main` first then find an ABI-compatible way to backport the functionality to Dome.

**Comment by chapulina** [comment]
This is awesome! Looking forward to the `ign-gazebo` PR! :rocket:

**Comment by atharva-18** [comment]
>There is a difference between how ogre and ogre2 handles shadows, e.g. semi-transparent objects also cast shadows in ogre2. We'll probably need to explicitly set cast shadows to be off in ogre2.

Got it. I think we can set cast shadows to be off in Gazebo itself.

>We promise ABI compatibility for released versions. Adding new virtual functions breaks ABI so these changes will need to go into the main branch and to be released in Ignition Fortress. Do you need this functionality in Dome? If so, we can try get these changes into main first then find an ABI-compatible way to backport the functionality to Dome.

Adding this feature to Dome is not a requirement for me as of now. I'll make changes to the Ignition F branch and create a new PR. Thanks for the info!

**Comment by atharva-18** [comment]
Closing this in favor of #314.

**Pull request closed without merging**
