### PR TITLE
Support setting horizontal and vertical resolution for GpuRays

### PR DESCRIPTION
**Pull request by nkoenig**
This allows horizontal and vertical resolution to be set on GpuRays.

This problem was found in Citadel (see [here](https://github.com/ignitionrobotics/ign-sensors/pull/86/files#r565840628)), but applying a non-breaking change to Citadel proved difficult.

Signed-off-by: Nate Koenig <nate@openrobotics.org>

### CODE REVIEW

**Comment by iche033** [comment]
changes looks good to me. Waiting for Windows CI fix in https://github.com/ignitionrobotics/ign-rendering/pull/228

**Comment by iche033** [comment]
CI looks good. Just some windows warnings:
https://build.osrfoundation.org/job/ign_rendering-pr-win/1288/msbuild/

**Review by mjcarroll — APPROVED** [review]
Looks good.

I think that there needs to be some documentation of what the units of the resolution parameters are.  I think it's supposed to be radians/increment, but I'm not 100% positive.

**Comment by mjcarroll** [comment]
@osrf-jenkins retest this please

**Comment by nkoenig** [comment]
> Looks good.
> 
> I think that there needs to be some documentation of what the units of the resolution parameters are. I think it's supposed to be radians/increment, but I'm not 100% positive.

I added more documentation in f41df6552b8717f340c5b8ce4fea1923d317bd06. Resolution is a factor and unitless.

**Review by iche033 — APPROVED** [review]

**Review by mjcarroll — APPROVED** [review]
Thanks for adding the doc, CI failure is unrelated.

**Pull request merged**
