### PR TITLE
Fix flaky thermal camera test on MacOS

### PR DESCRIPTION
**Pull request by adlarkin**
Signed-off-by: Ashton Larkin <ashton@openrobotics.org>

# Bug Report

Trying to fix the new test failure introduced in https://github.com/ignitionrobotics/ign-rendering/pull/246#issuecomment-777937844.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See
  [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See
  [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review
[another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+archived%3Afalse+)
to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by adlarkin** [comment]
MacOS failed again. Taking a closer look at the results from CI show this:

```
/Users/jenkins/workspace/ignition_rendering-ci-pr_any-homebrew-amd64/ign-rendering/test/integration/thermal_camera.cc:233
The difference between boxTemp and temp is 14, which exceeds boxTempRange, where
boxTemp evaluates to 310,
temp evaluates to 296, and
boxTempRange evaluates to 3.
i is 48 j is 4
```

So, it looks like there's only one pixel in the whole image that fails the check, and it's near the bottom-left of the image. I'm not sure why this is.

**Comment by adlarkin** [comment]
I tried sleeping for a bit (https://github.com/ignitionrobotics/ign-rendering/pull/247/commits/4a72707640f62344a92514e1f559f27750e65dfc) after each camera update to make sure the message was received, but that didn't seem to help. I am getting the same failure that I mentioned [above](https://github.com/ignitionrobotics/ign-rendering/pull/247#issuecomment-778495448).

**Comment by chapulina** [comment]
@adlarkin , what's the status of this PR? Are you still iterating?

**Comment by adlarkin** [comment]
> what's the status of this PR? Are you still iterating?

No, I haven't re-visited this for a long time (in fact, I forgot this PR was still open :upside_down_face:). I'm closing this.

**Pull request closed without merging**
