### PR TITLE
6 ➡️ 7 (main)

### PR DESCRIPTION
**Pull request by chapulina**
# ➡️ Forward port

Port `ign-rendering6` to `main`

Branch comparison: https://github.com/ignitionrobotics/ign-rendering/compare/main...ign-rendering6

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Review by ahcorde — APPROVED** [review]

**Comment by chapulina** [comment]
humm there are tons of test failures on Focal which seem unrelated to this PR

**Comment by iche033** [comment]
hmm weird the last merge forward was still fine: https://github.com/ignitionrobotics/ign-rendering/pull/602

The tests pass locally. Going to retrigger builds to double check

**Comment by iche033** [comment]
just updated my ignition workspace. Tests and examples are crashing. It could be related to https://github.com/ignitionrobotics/ign-common/pull/319

**Comment by adlarkin** [comment]
@iche033 it looks like a fix was made in https://github.com/ignitionrobotics/ign-common/pull/338, would you mind updating your workspace and trying again?

**Comment by iche033** [comment]
yep that fixes the issue!

**Pull request merged**
