### PR TITLE
Update test configuration to use ogre2

### PR DESCRIPTION
**Pull request by iche033**
see  ignitionrobotics/ign-gazebo#14

May need to fix CI...

### CODE REVIEW

**Comment by chapulina** [comment]
Interesting that no `ogre2` files are showing on the coverage report: https://codecov.io/gh/ignitionrobotics/ign-rendering/tree/17af7b8296830b2f45e165a432611ed2ef855ccc/src

**Comment by iche033** [comment]
ok CI should be working. More tests are passing on windows compared to ogre 1.x even though there are still issues with loading the render engine plugin.

**Comment by chapulina** [comment]
Should we try to address the new test failure on homebrew?

https://build.osrfoundation.org/job/ignition_rendering-ci-pr_any-homebrew-amd64/666/testReport/junit/(root)/DepthCamera_DepthCameraTest/DepthCameraBoxes_ogre2/

`ign-rendering3` has a clean track record: https://build.osrfoundation.org/job/ignition_rendering-ci-ign-rendering3-homebrew-amd64/

**Comment by iche033** [comment]
disabled DepthCamera test and ticketed issue #108 

This PR is ready for review again

**Pull request merged**
