### PR TITLE
3 -> 4

### PR DESCRIPTION
**Pull request by iche033**
# ➡️ Forward port

Port ign-rendering3 to ign-rendering4

Branch comparison: https://github.com/ignitionrobotics/ign-rendering/compare/ign-rendering4...ign-rendering3

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Review by chapulina — APPROVED** [review]

**Comment by iche033** [comment]
hmm the `INTEGRATION_depth_camera` test is failing on homebrew after porting to ign-rendering4. It's failing on checks that are related to #332

**Comment by chapulina** [comment]
> I'll probably just disable it in ign-rendering4

Homebrew is green on the latest commit, and I think you haven't disabled the test yet, right? Is it flaky?

**Comment by iche033** [comment]
I haven't disabled the test. I just hit retry on the build. So I think the test is flaky. So far, test passed 1 out 3 times in this PR.

**Comment by chapulina** [comment]
Got it, I'll leave it up to you if you want to leave it flaky for a while or disable it. I'd like to get this PR in soon so we can make a new 4.X release to unblock downstream PRs.

**Comment by iche033** [comment]
added ifdef for apple around the checks that fail instead of disabling the whole test 0551b74

**Comment by iche033** [comment]
all builds green. Merging.

**Pull request merged**
