### PR TITLE
6 -> main

### PR DESCRIPTION
**Pull request by iche033**
# ➡️ Forward port

Port ign-rendering6 to main

Branch comparison: https://github.com/ignitionrobotics/ign-rendering/compare/main...ign-rendering6

**Note to maintainers**: Remember to **Merge** with commit (not squash-merge or rebase)

### CODE REVIEW

**Comment by iche033** [comment]
that test is failing on `ign-rendering6` as well. It's fixed as part of https://github.com/ignitionrobotics/ign-rendering/pull/446. I can separate the changes out to a separate PR.

**Comment by iche033** [comment]
> I can separate the changes out to a separate PR.

https://github.com/ignitionrobotics/ign-rendering/pull/481

**Review by ahcorde — APPROVED** [review]
DCO is failing

**Comment by iche033** [comment]
it always seems to be failing on forward ports. I haven't figured out the correct solution to it yet. I've manually set DCO to pass.

**Pull request merged**
