### PR TITLE
Per-point colors in point clouds

### PR DESCRIPTION
**Pull request by chapulina**
# 🎉 New feature

* Part of https://github.com/ignitionrobotics/ign-gazebo/issues/1156
* Needed by https://github.com/ignitionrobotics/ign-gui/pull/318

## Summary

We have been populating the `colors` vector in `Ogre2DynamicRenderable`, but not using the colors for anything.

For most dynamic renderables, we fill the vertex buffer with position and normal. But points don't have normals, so we've been leaving half the buffer empty. The implementation on this PR takes advantage of those empty slots to place per-point colors (only RGB, no A).

Thanks @WilliamLewww for helping me out with this!

## Test it

The marker example on https://github.com/ignitionrobotics/ign-gui/pull/318 uses this:

pts_color

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [x] Updated documentation (as needed)
- [x] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Comment by iche033** [comment]
works for me. I made some changes in the [iche033/6/marker_point_color](https://github.com/ignitionrobotics/ign-rendering/commit/5df748eb48cff2fb60b544501da6afcdd5a8ec28) branch for Metal. I don't have a working mac setup to test it though.

Using the `normal` buffer is fine. I know that in ogre 1.x, you can create vertex element of type `VES_DIFFUSE` to store colors per vertex (e.g. in place of `VES_NORMAL` if `operationType` is point list) but I couldn't find examples that does it in ogre 2.x so not sure how well it's working. Otherwise, that would probably be a more semantically correct way to pass colors to shaders.

**Comment by chapulina** [comment]
> I made some changes in the iche033/6/marker_point_color branch for Metal.

Thanks! Merged in.

**Comment by chapulina** [comment]
FYI, I rebased this PR to Garden (`main`), because downstream PRs have breaking changes that need to target Garden. If there's a need to backport this to Fortress later I can open a separate PR.

**Review by iche033 — APPROVED** [review]
looks good to me.

**Pull request merged**
