### PR TITLE
Adds Mesh Tutorial.

### PR DESCRIPTION
**Pull request by francocipollone**
Signed-off-by: Franco Cipollone <franco.c@ekumenlabs.com>

# 🎉 New feature

## Summary

The mesh tutorial [here created](https://docs.google.com/document/d/18rf5p6OTQ_Fpp-cHAFvcCcETtJG7N9FPcHoqfOEAxjU/edit?usp=sharing) is migrated from Google Doc to an actual tutorial in `ign-rendering`
**Tutorial Author**: @RafiAbdullah

Some pics:
image

image

## Test it

I share here the generated HTML  in case you want to take a look:

[tutorial_model_and_optimize_meshes.zip](https://github.com/ignitionrobotics/ign-rendering/files/6718144/tutorial_model_and_optimize_meshes.zip)

After extracting the files you can use your favorite browser by doing: (e.g. using google chrome)
```
google-chrome model_and_optimize_meshes.html
``` 

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [x] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by chapulina** [comment]
Thank you for the tutorial, @francocipollone ! I don't remember if I was the one who suggested putting it in `ign-rendering`, but looking at it now, since it touches simulation concepts like collision, I think the tutorial should be in `ign-gazebo` instead. What do you think?

**Comment by francocipollone** [comment]
> Thank you for the tutorial, @francocipollone ! I don't remember if I was the one who suggested putting it in `ign-rendering`, but looking at it now, since it touches simulation concepts like collision, I think the tutorial should be in `ign-gazebo` instead. What do you think?

Yeah I asked you about it on Slack. :smile: . It it true it mentions some simulation concepts, I could close it and replicate it in `ign-gazebo` then

**Comment by chapulina** [comment]
> Yeah I asked you about it on Slack. smile 

Ha I thought so :see_no_evil: 

> I could close it and replicate it in ign-gazebo then

Thanks! I must have not realized earlier that it touched simulation-specific concepts :bowing_woman:

**Comment by francocipollone** [comment]
Closed in favor of https://github.com/ignitionrobotics/ign-gazebo/pull/915

**Pull request closed without merging**
