### PR TITLE
Add SetSize API for Marker point size

### PR DESCRIPTION
**Pull request by iche033**
# 🎉 New feature

## Summary

Similar to #392, this PR add new function for setting size of a marker with `MT_POINTS` points

## Test it

It may be worth considering adding a marker example demo in the future for demo'ing the marker feature and it's also easier for testing.

For now, I test with the the [marker](https://github.com/ignitionrobotics/ign-gui/tree/main/examples/standalone/marker) standable example in ign-gui, and then manually modifying the marker size in ign-gazebo's `MarkerManager`

1. Build the ign-gui [marker](https://github.com/ignitionrobotics/ign-gui/tree/main/examples/standalone/marker) example

1.  We currently don't have a gui plugin or msg field for changing marker size. So manually test different marker size by applying this patch to ign-gazebo.

    ```cpp
    diff --git a/src/rendering/MarkerManager.cc b/src/rendering/MarkerManager.cc
    index 736815b4..4e64e096 100644
    --- a/src/rendering/MarkerManager.cc
    +++ b/src/rendering/MarkerManager.cc
    @@ -321,6 +321,7 @@ void MarkerManagerPrivate::SetMarker(const ignition::msgs::Marker &_msg,
       // Set Marker Render Type
       ignition::rendering::MarkerType markerType = MsgToType(_msg);
       _markerPtr->SetType(markerType);
    +  _markerPtr->SetSize(5.0);
     
       // Set Marker Material
       if (_msg.has_material())
        ```
1. rebuild and launch ign-gazebo

    ```
    ign gazebo -v 4 -r
    ```

1. In another terminal, run the ign-gui `marker` demo to see large points drawn in ign-gazebo near the end of the demo before all markers are erased:

marker_point_size

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Review by ahcorde — CHANGES_REQUESTED** [review]
Windows is failing

```bash
C:\Jenkins\workspace\ign_rendering-pr-win\ws\ign-rendering\ogre\src\OgreMarker.cc(65,70): error C2664: 'void Ogre::SimpleRenderable::setMaterial(const Ogre::MaterialPtr &)': cannot convert argument 1 from 'const char [16]' to 'const Ogre::MaterialPtr &' [C:\Jenkins\workspace\ign_rendering-pr-win\ws\build\ignition-rendering6\ogre\src\ignition-rendering6-ogre.vcxproj]

C:\Jenkins\workspace\ign_rendering-pr-win\ws\ign-rendering\ogre\src\OgreMarker.cc(65,70): message : Reason: cannot convert from 'const char [16]' to 'const Ogre::MaterialPtr' [C:\Jenkins\workspace\ign_rendering-pr-win\ws\build\ignition-rendering6\ogre\src\ignition-rendering6-ogre.vcxproj]

C:\Jenkins\workspace\ign_rendering-pr-win\ws\ign-rendering\ogre\src\OgreMarker.cc(65,70): message : Constructor for class 'Ogre::SharedPtr<Ogre::Material>' is declared 'explicit' [C:\Jenkins\workspace\ign_rendering-pr-win\ws\build\ignition-rendering6\ogre\src\ignition-rendering6-ogre.vcxproj]

C:\vcpkg\installed\x64-windows\include\OGRE\OgreSimpleRenderable.h(76,22): message : see declaration of 'Ogre::SimpleRenderable::setMaterial' (compiling source file C:\Jenkins\workspace\ign_rendering-pr-win\ws\ign-rendering\ogre\src\OgreMarker.cc) [C:\Jenkins\workspace\ign_rendering-pr-win\ws\build\ignition-rendering6\ogre\src\ignition-rendering6-ogre.vcxproj]
```

**Review by ahcorde — APPROVED** [review]

**Comment by ahcorde** [comment]
@iche033 are you planning to merge this on top of the other PR ? or are you going to change the base when the other one is merged ?

**Comment by chapulina** [comment]
> @iche033 are you planning to merge this on top of the other PR ? 

Technically, this one can't go directly into `main` because it was opened after feature freeze, so I think it's best to bundle it with #392

**Comment by chapulina** [comment]
Merging into #392 :wink:

**Pull request merged**
