### PR TITLE
[wip] Added transparent mode

### PR DESCRIPTION
**Pull request by atharva-18**
# 🎉 New feature
## Summary
Adds transparent mode to visuals
transparent

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by ahcorde** [comment]
TODO

 - [ ] Add transparent to `visualization_demo` when this PR is in https://github.com/ignitionrobotics/ign-rendering/pull/326/files

**Comment by iche033** [comment]
transparency settings can be set through the Material class. Is it not working for your needs?

**Comment by atharva-18** [comment]
> transparency settings can be set through the Material class. Is it not working for your needs?

I wanted to set the transparency for a particular visual rather than a material being used by multiple visuals, similar to the `View as transparent` mode in Gazebo classic.

**Comment by iche033** [comment]
I see. To do that, we need to make sure the material that each visual has is unique. That's done when the material is set, i.e. `visual->SetMaterial(mat, true)`, with the second arg telling the visual to clone the material first so it now has a copy instead of an instance of the material. Afterwards, you can do:

```
auto mat = visual->Material();
mat->SetTransparency(...);
```

Then it should only affect that particular visual. 

It's the same idea that's implemented in gazebo classic, except the transparency logic is being handled in the Material class instead of the Visual class.

**Comment by atharva-18** [comment]
> I see. To do that, we need to make sure the material that each visual has is unique. That's done when the material is set, i.e. `visual->SetMaterial(mat, true)`, with the second arg telling the visual to clone the material first so it now has a copy instead of an instance of the material. Afterwards, you can do:
> 
> ```
> auto mat = visual->Material();
> mat->SetTransparency(...);
> ```
> 
> Then it should only affect that particular visual.
> 
> It's the same idea that's implemented in gazebo classic, except the transparency logic is being handled in the Material class instead of the Visual class.

This would be a better approach. I think we can move the transparency logic to ign-gazebo (since the material is cloned for each visual) -
```
auto mat = visual->Material();

if (showTransp)
  mat->SetTransparency(0.5);
else
  mat->SetTransparency(0.0);
```

**Review by ahcorde — APPROVED** [review]

**Review by ahcorde — CHANGES_REQUESTED** [review]
@atharva-18, is this ready to merge?

Transparency test is failing on MacOS

https://build.osrfoundation.org/job/ignition_rendering-ci-pr_any-homebrew-amd64/1569/testReport/junit/(root)/Visual_VisualTest/Transparency_ogre2/

**Comment by atharva-18** [comment]
@ahcorde I have moved the transparency logic to `ign-gazebo` (as @iche033 suggested) since the material is cloned for each visual. This is similar to the `Align Tool` plugin.

**Comment by chapulina** [comment]
> I have moved the transparency logic to ign-gazebo

Thanks, @atharva-18 . Does this mean this PR can be closed?

**Comment by atharva-18** [comment]
> > I have moved the transparency logic to ign-gazebo
> 
> Thanks, @atharva-18 . Does this mean this PR can be closed?

Yes, we can close this PR.

**Pull request closed without merging**
