### PR TITLE
[ign-rendering3] Workflow updates

### PR DESCRIPTION
**Pull request by chapulina**
* Add [labeler workflow](https://github.com/ignition-tooling/pr-collection-labeler)
* Add [triage workflow](https://github.com/marketplace/actions/create-project-card-action)
* Add [Ubuntu CI workflow with Codecov upload](https://github.com/ignition-tooling/ubuntu-bionic-ci-action)
* Update codecov badge
* Port `CODEOWNERS`

### CODE REVIEW

**Comment by iche033** [comment]
should I expect to see a codecov.io comment in the PR?

**Comment by chapulina** [comment]
> should I expect to see a codecov.io comment in the PR?

Yup, fixed!

**Comment by chapulina** [comment]
The test coverage is really low for all branches. I'm not sure why and didn't look too close at the logs, some guesses:

* Optix not being installed means we lose about 1/3 of coverage
* GitHub actions doesn't support GPU tests

At least some tests are running though, so I think we can close https://github.com/ignitionrobotics/ign-rendering/issues/44.

**Comment by iche033** [comment]
I think it's also running for ogre 1.x only and another 1/3 of coverage lost

**Comment by chapulina** [comment]
Oh that reminds me of this issue, which I _think_ I put on `ign-gazebo` by mistake, when I meant to put it on `ign-rendering` https://github.com/ignitionrobotics/ign-gazebo/issues/14

**Pull request merged**
