### PR TITLE
Add Ubuntu Jammy CI

### PR DESCRIPTION
**Pull request by scpeters**
# 🦟 Bug fix

Part of https://github.com/ignition-tooling/release-tools/issues/566

## Summary

Enable CI for Ubuntu 22.04 (Jammy)

## Checklist
- [X] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by scpeters** [comment]
this needs libogre-2.2-dev for jammy

**Comment by chapulina** [comment]
> this needs libogre-2.2-dev for jammy

@j-rivero , did we get any version of Ogre 2.X upstreamed to Ubuntu?

**Comment by j-rivero** [comment]
> @j-rivero , did we get any version of Ogre 2.X upstreamed to Ubuntu?

It took a while but yes https://packages.ubuntu.com/uk/jammy/libogre-next-dev

**Comment by scpeters** [comment]
> > @j-rivero , did we get any version of Ogre 2.X upstreamed to Ubuntu?
> 
> It took a while but yes https://packages.ubuntu.com/uk/jammy/libogre-next-dev
> 
> Let me add that we still need IgnOGRE2 support for it, since it provides a custom CMake helper that can potentially work almost by its own, more info in [ignitionrobotics/ign-cmake#208](https://github.com/ignitionrobotics/ign-cmake/issues/208)

I've moved the ogre2.2 package to distro-specific `packages-*.apt` files and used `libogre-next-dev` in `packages-jammy.apt` in https://github.com/ignitionrobotics/ign-rendering/pull/577/commits/c40722be29330b67911b6e7a7f8cf5e8e4630fe4

**Comment by scpeters** [comment]
Jammy CI is not failing now, but it's also not finding the ogre-next package:

~~~
-- Skipping component [ogre2]: Missing dependency [IgnOGRE2] (Components: HlmsPbs, HlmsUnlit, Overlay).
        ^~~~~ Set SKIP_ogre2=true in cmake to suppress this warning.
~~~

**Review by chapulina — APPROVED** [review]
Nice!

```
   -- Checking for module 'OGRE-Next'
  --   Found OGRE-Next, version 2.2.5
  -- /usr/include/OGRE-Next/
  -- /usr/include/OGRE-Next/
  -- Found Ogre  (2.2.5)
```

**Comment by chapulina** [comment]
This PR was reverted with a commit directly to `ign-rendering6`: https://github.com/ignitionrobotics/ign-rendering/commit/92bbff379ab3a7915f59373bd26b6804de77575e

**Pull request merged**
