### PR TITLE
4.3.0

### PR DESCRIPTION
**Pull request by adlarkin**
Prepare for 4.3.0 release.

Comparison to 4.2.0: https://github.com/ignitionrobotics/ign-rendering/compare/ignition-rendering4_4.2.0...ign-rendering4

Signed-off-by: Ashton Larkin <ashton@openrobotics.org>

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]
LGTM

**Comment by adlarkin** [comment]
I'm seeing some failed checks, but it seems like they are inconsistent. A lot of them are test failures do to something like this:
```
  [Err] [Ogre2RenderEngine.cc:342] Unable to open display: :1.0
  [Err] [Ogre2RenderEngine.cc:739]  Unable to create the rendering window
```

For example, if you look at #189, all checks passed on that PR, but here, the integration thermal camera test fails some of the checks. I believe we can ignore this, but can anyone confirm?

**Comment by chapulina** [comment]
Yeah that was a lot of failing tests. It could be a spurious infra problem. I retriggered the build, let's see how it comes back.

**Comment by nkoenig** [comment]
The `thermal_system` test is not listed in the `tests_needing_display` in the `test/integration/CMakelists.txt` file. I haven't checked the test, but I think you might need to make this move.

**Comment by adlarkin** [comment]
> The `thermal_system` test is not listed in the `tests_needing_display` in the `test/integration/CMakelists.txt` file. I haven't checked the test, but I think you might need to make this move.

I can add this in, but if this was the problem, then wouldn't this mean that the tests would have failed in #189 as well? I think that there might be a problem with Optimus because the last CI results show quite a bit of test failures: https://build.osrfoundation.org/job/ignition_rendering-ci-pr_any-ubuntu_auto-amd64/1022/

**Comment by nkoenig** [comment]
Good point. It looks like #189 completed just fine, so no need to change the code.

**Comment by adlarkin** [comment]
I'm waiting for #224 to get merged before merging this.

**Comment by adlarkin** [comment]
#224 has been merged, so this has been updated accordingly. Can I get one more review of this?

**Review by chapulina — APPROVED** [review]

**Review by iche033 — APPROVED** [review]

**Pull request merged**
